/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FastEndpointsErrorResponse,
  TodoApiEndpointsTodosCompactCommandsCreateTodoRequest,
  TodoApiEndpointsTodosCompactCommandsCreateTodoResponse,
  TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest,
  TodoApiEndpointsTodosCompactQueriesGetTodoResponse,
  TodoApiEndpointsTodosCompactQueriesListTodosResponse,
} from '../models/index';
import {
    FastEndpointsErrorResponseFromJSON,
    FastEndpointsErrorResponseToJSON,
    TodoApiEndpointsTodosCompactCommandsCreateTodoRequestFromJSON,
    TodoApiEndpointsTodosCompactCommandsCreateTodoRequestToJSON,
    TodoApiEndpointsTodosCompactCommandsCreateTodoResponseFromJSON,
    TodoApiEndpointsTodosCompactCommandsCreateTodoResponseToJSON,
    TodoApiEndpointsTodosCompactCommandsUpdateTodoRequestFromJSON,
    TodoApiEndpointsTodosCompactCommandsUpdateTodoRequestToJSON,
    TodoApiEndpointsTodosCompactQueriesGetTodoResponseFromJSON,
    TodoApiEndpointsTodosCompactQueriesGetTodoResponseToJSON,
    TodoApiEndpointsTodosCompactQueriesListTodosResponseFromJSON,
    TodoApiEndpointsTodosCompactQueriesListTodosResponseToJSON,
} from '../models/index';

export interface TodoApiEndpointsTodosCompactCommandsCreateTodoOperationRequest {
    todoApiEndpointsTodosCompactCommandsCreateTodoRequest: TodoApiEndpointsTodosCompactCommandsCreateTodoRequest;
}

export interface TodoApiEndpointsTodosCompactCommandsDeleteTodoRequest {
    id: number;
}

export interface TodoApiEndpointsTodosCompactCommandsUpdateTodoOperationRequest {
    id: number;
    todoApiEndpointsTodosCompactCommandsUpdateTodoRequest: TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest;
}

export interface TodoApiEndpointsTodosCompactQueriesGetTodoRequest {
    id: number;
}

/**
 * 
 */
export class TodoscompactApi extends runtime.BaseAPI {

    /**
     */
    async todoApiEndpointsTodosCompactCommandsCreateTodoRaw(requestParameters: TodoApiEndpointsTodosCompactCommandsCreateTodoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoApiEndpointsTodosCompactCommandsCreateTodoResponse>> {
        if (requestParameters['todoApiEndpointsTodosCompactCommandsCreateTodoRequest'] == null) {
            throw new runtime.RequiredError(
                'todoApiEndpointsTodosCompactCommandsCreateTodoRequest',
                'Required parameter "todoApiEndpointsTodosCompactCommandsCreateTodoRequest" was null or undefined when calling todoApiEndpointsTodosCompactCommandsCreateTodo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/todoscompact/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TodoApiEndpointsTodosCompactCommandsCreateTodoRequestToJSON(requestParameters['todoApiEndpointsTodosCompactCommandsCreateTodoRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoApiEndpointsTodosCompactCommandsCreateTodoResponseFromJSON(jsonValue));
    }

    /**
     */
    async todoApiEndpointsTodosCompactCommandsCreateTodo(requestParameters: TodoApiEndpointsTodosCompactCommandsCreateTodoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoApiEndpointsTodosCompactCommandsCreateTodoResponse> {
        const response = await this.todoApiEndpointsTodosCompactCommandsCreateTodoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async todoApiEndpointsTodosCompactCommandsDeleteTodoRaw(requestParameters: TodoApiEndpointsTodosCompactCommandsDeleteTodoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling todoApiEndpointsTodosCompactCommandsDeleteTodo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/todoscompact/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async todoApiEndpointsTodosCompactCommandsDeleteTodo(requestParameters: TodoApiEndpointsTodosCompactCommandsDeleteTodoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.todoApiEndpointsTodosCompactCommandsDeleteTodoRaw(requestParameters, initOverrides);
    }

    /**
     */
    async todoApiEndpointsTodosCompactCommandsUpdateTodoRaw(requestParameters: TodoApiEndpointsTodosCompactCommandsUpdateTodoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling todoApiEndpointsTodosCompactCommandsUpdateTodo().'
            );
        }

        if (requestParameters['todoApiEndpointsTodosCompactCommandsUpdateTodoRequest'] == null) {
            throw new runtime.RequiredError(
                'todoApiEndpointsTodosCompactCommandsUpdateTodoRequest',
                'Required parameter "todoApiEndpointsTodosCompactCommandsUpdateTodoRequest" was null or undefined when calling todoApiEndpointsTodosCompactCommandsUpdateTodo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/todoscompact/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TodoApiEndpointsTodosCompactCommandsUpdateTodoRequestToJSON(requestParameters['todoApiEndpointsTodosCompactCommandsUpdateTodoRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async todoApiEndpointsTodosCompactCommandsUpdateTodo(requestParameters: TodoApiEndpointsTodosCompactCommandsUpdateTodoOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.todoApiEndpointsTodosCompactCommandsUpdateTodoRaw(requestParameters, initOverrides);
    }

    /**
     */
    async todoApiEndpointsTodosCompactQueriesGetTodoRaw(requestParameters: TodoApiEndpointsTodosCompactQueriesGetTodoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoApiEndpointsTodosCompactQueriesGetTodoResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling todoApiEndpointsTodosCompactQueriesGetTodo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/todoscompact/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoApiEndpointsTodosCompactQueriesGetTodoResponseFromJSON(jsonValue));
    }

    /**
     */
    async todoApiEndpointsTodosCompactQueriesGetTodo(requestParameters: TodoApiEndpointsTodosCompactQueriesGetTodoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoApiEndpointsTodosCompactQueriesGetTodoResponse> {
        const response = await this.todoApiEndpointsTodosCompactQueriesGetTodoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async todoApiEndpointsTodosCompactQueriesListTodosRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoApiEndpointsTodosCompactQueriesListTodosResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/todoscompact`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoApiEndpointsTodosCompactQueriesListTodosResponseFromJSON(jsonValue));
    }

    /**
     */
    async todoApiEndpointsTodosCompactQueriesListTodos(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoApiEndpointsTodosCompactQueriesListTodosResponse> {
        const response = await this.todoApiEndpointsTodosCompactQueriesListTodosRaw(initOverrides);
        return await response.value();
    }

}
