/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FastEndpointsErrorResponse,
  TodoApiEndpointsTodosCreateTodoCreateTodoRequest,
  TodoApiEndpointsTodosCreateTodoCreateTodoResponse,
  TodoApiEndpointsTodosGetTodoGetTodoResponse,
  TodoApiEndpointsTodosListTodosListTodosResponse,
  TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest,
} from '../models/index';
import {
    FastEndpointsErrorResponseFromJSON,
    FastEndpointsErrorResponseToJSON,
    TodoApiEndpointsTodosCreateTodoCreateTodoRequestFromJSON,
    TodoApiEndpointsTodosCreateTodoCreateTodoRequestToJSON,
    TodoApiEndpointsTodosCreateTodoCreateTodoResponseFromJSON,
    TodoApiEndpointsTodosCreateTodoCreateTodoResponseToJSON,
    TodoApiEndpointsTodosGetTodoGetTodoResponseFromJSON,
    TodoApiEndpointsTodosGetTodoGetTodoResponseToJSON,
    TodoApiEndpointsTodosListTodosListTodosResponseFromJSON,
    TodoApiEndpointsTodosListTodosListTodosResponseToJSON,
    TodoApiEndpointsTodosUpdateTodoUpdateTodoRequestFromJSON,
    TodoApiEndpointsTodosUpdateTodoUpdateTodoRequestToJSON,
} from '../models/index';

export interface TodoApiEndpointsTodosCreateTodoCreateTodoEndpointRequest {
    todoApiEndpointsTodosCreateTodoCreateTodoRequest: TodoApiEndpointsTodosCreateTodoCreateTodoRequest;
}

export interface TodoApiEndpointsTodosDeleteTodoDeleteTodoRequest {
    id: number;
}

export interface TodoApiEndpointsTodosGetTodoGetTodoEndpointRequest {
    id: number;
}

export interface TodoApiEndpointsTodosUpdateTodoUpdateTodoEndpointRequest {
    id: number;
    todoApiEndpointsTodosUpdateTodoUpdateTodoRequest: TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest;
}

/**
 * 
 */
export class TodosApi extends runtime.BaseAPI {

    /**
     */
    async todoApiEndpointsTodosCreateTodoCreateTodoEndpointRaw(requestParameters: TodoApiEndpointsTodosCreateTodoCreateTodoEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoApiEndpointsTodosCreateTodoCreateTodoResponse>> {
        if (requestParameters['todoApiEndpointsTodosCreateTodoCreateTodoRequest'] == null) {
            throw new runtime.RequiredError(
                'todoApiEndpointsTodosCreateTodoCreateTodoRequest',
                'Required parameter "todoApiEndpointsTodosCreateTodoCreateTodoRequest" was null or undefined when calling todoApiEndpointsTodosCreateTodoCreateTodoEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/todos/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TodoApiEndpointsTodosCreateTodoCreateTodoRequestToJSON(requestParameters['todoApiEndpointsTodosCreateTodoCreateTodoRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoApiEndpointsTodosCreateTodoCreateTodoResponseFromJSON(jsonValue));
    }

    /**
     */
    async todoApiEndpointsTodosCreateTodoCreateTodoEndpoint(requestParameters: TodoApiEndpointsTodosCreateTodoCreateTodoEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoApiEndpointsTodosCreateTodoCreateTodoResponse> {
        const response = await this.todoApiEndpointsTodosCreateTodoCreateTodoEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async todoApiEndpointsTodosDeleteTodoDeleteTodoRaw(requestParameters: TodoApiEndpointsTodosDeleteTodoDeleteTodoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling todoApiEndpointsTodosDeleteTodoDeleteTodo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/todos/delete/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async todoApiEndpointsTodosDeleteTodoDeleteTodo(requestParameters: TodoApiEndpointsTodosDeleteTodoDeleteTodoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.todoApiEndpointsTodosDeleteTodoDeleteTodoRaw(requestParameters, initOverrides);
    }

    /**
     */
    async todoApiEndpointsTodosGetTodoGetTodoEndpointRaw(requestParameters: TodoApiEndpointsTodosGetTodoGetTodoEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoApiEndpointsTodosGetTodoGetTodoResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling todoApiEndpointsTodosGetTodoGetTodoEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/todos/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoApiEndpointsTodosGetTodoGetTodoResponseFromJSON(jsonValue));
    }

    /**
     */
    async todoApiEndpointsTodosGetTodoGetTodoEndpoint(requestParameters: TodoApiEndpointsTodosGetTodoGetTodoEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoApiEndpointsTodosGetTodoGetTodoResponse> {
        const response = await this.todoApiEndpointsTodosGetTodoGetTodoEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async todoApiEndpointsTodosListTodosListTodosEndpointRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoApiEndpointsTodosListTodosListTodosResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/todos`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoApiEndpointsTodosListTodosListTodosResponseFromJSON(jsonValue));
    }

    /**
     */
    async todoApiEndpointsTodosListTodosListTodosEndpoint(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoApiEndpointsTodosListTodosListTodosResponse> {
        const response = await this.todoApiEndpointsTodosListTodosListTodosEndpointRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async todoApiEndpointsTodosUpdateTodoUpdateTodoEndpointRaw(requestParameters: TodoApiEndpointsTodosUpdateTodoUpdateTodoEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling todoApiEndpointsTodosUpdateTodoUpdateTodoEndpoint().'
            );
        }

        if (requestParameters['todoApiEndpointsTodosUpdateTodoUpdateTodoRequest'] == null) {
            throw new runtime.RequiredError(
                'todoApiEndpointsTodosUpdateTodoUpdateTodoRequest',
                'Required parameter "todoApiEndpointsTodosUpdateTodoUpdateTodoRequest" was null or undefined when calling todoApiEndpointsTodosUpdateTodoUpdateTodoEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/todos/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TodoApiEndpointsTodosUpdateTodoUpdateTodoRequestToJSON(requestParameters['todoApiEndpointsTodosUpdateTodoUpdateTodoRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async todoApiEndpointsTodosUpdateTodoUpdateTodoEndpoint(requestParameters: TodoApiEndpointsTodosUpdateTodoUpdateTodoEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.todoApiEndpointsTodosUpdateTodoUpdateTodoEndpointRaw(requestParameters, initOverrides);
    }

}
