/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * the dto used to send an error response to the client
 * @export
 * @interface FastEndpointsErrorResponse
 */
export interface FastEndpointsErrorResponse {
    /**
     * the http status code sent to the client. default is 400.
     * @type {number}
     * @memberof FastEndpointsErrorResponse
     */
    statusCode?: number;
    /**
     * the message for the error response
     * @type {string}
     * @memberof FastEndpointsErrorResponse
     */
    message?: string;
    /**
     * the collection of errors for the current context
     * @type {{ [key: string]: Array<string>; }}
     * @memberof FastEndpointsErrorResponse
     */
    errors?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the FastEndpointsErrorResponse interface.
 */
export function instanceOfFastEndpointsErrorResponse(value: object): value is FastEndpointsErrorResponse {
    return true;
}

export function FastEndpointsErrorResponseFromJSON(json: any): FastEndpointsErrorResponse {
    return FastEndpointsErrorResponseFromJSONTyped(json, false);
}

export function FastEndpointsErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FastEndpointsErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function FastEndpointsErrorResponseToJSON(json: any): FastEndpointsErrorResponse {
    return FastEndpointsErrorResponseToJSONTyped(json, false);
}

export function FastEndpointsErrorResponseToJSONTyped(value?: FastEndpointsErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'errors': value['errors'],
    };
}

