/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosGetTodoGetTodoResponse
 */
export interface TodoApiEndpointsTodosGetTodoGetTodoResponse {
    /**
     * 
     * @type {string}
     * @memberof TodoApiEndpointsTodosGetTodoGetTodoResponse
     */
    title?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoApiEndpointsTodosGetTodoGetTodoResponse
     */
    done?: boolean;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosGetTodoGetTodoResponse interface.
 */
export function instanceOfTodoApiEndpointsTodosGetTodoGetTodoResponse(value: object): value is TodoApiEndpointsTodosGetTodoGetTodoResponse {
    return true;
}

export function TodoApiEndpointsTodosGetTodoGetTodoResponseFromJSON(json: any): TodoApiEndpointsTodosGetTodoGetTodoResponse {
    return TodoApiEndpointsTodosGetTodoGetTodoResponseFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosGetTodoGetTodoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosGetTodoGetTodoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'done': json['done'] == null ? undefined : json['done'],
    };
}

export function TodoApiEndpointsTodosGetTodoGetTodoResponseToJSON(json: any): TodoApiEndpointsTodosGetTodoGetTodoResponse {
    return TodoApiEndpointsTodosGetTodoGetTodoResponseToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosGetTodoGetTodoResponseToJSONTyped(value?: TodoApiEndpointsTodosGetTodoGetTodoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'done': value['done'],
    };
}

