/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosCreateTodoCreateTodoRequest
 */
export interface TodoApiEndpointsTodosCreateTodoCreateTodoRequest {
    /**
     * 
     * @type {string}
     * @memberof TodoApiEndpointsTodosCreateTodoCreateTodoRequest
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoApiEndpointsTodosCreateTodoCreateTodoRequest
     */
    done?: boolean;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosCreateTodoCreateTodoRequest interface.
 */
export function instanceOfTodoApiEndpointsTodosCreateTodoCreateTodoRequest(value: object): value is TodoApiEndpointsTodosCreateTodoCreateTodoRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TodoApiEndpointsTodosCreateTodoCreateTodoRequestFromJSON(json: any): TodoApiEndpointsTodosCreateTodoCreateTodoRequest {
    return TodoApiEndpointsTodosCreateTodoCreateTodoRequestFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCreateTodoCreateTodoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosCreateTodoCreateTodoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'done': json['done'] == null ? undefined : json['done'],
    };
}

export function TodoApiEndpointsTodosCreateTodoCreateTodoRequestToJSON(json: any): TodoApiEndpointsTodosCreateTodoCreateTodoRequest {
    return TodoApiEndpointsTodosCreateTodoCreateTodoRequestToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCreateTodoCreateTodoRequestToJSONTyped(value?: TodoApiEndpointsTodosCreateTodoCreateTodoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'done': value['done'],
    };
}

