/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TodoApiEndpointsTodosCompactQueriesTodoItem } from './TodoApiEndpointsTodosCompactQueriesTodoItem';
import {
    TodoApiEndpointsTodosCompactQueriesTodoItemFromJSON,
    TodoApiEndpointsTodosCompactQueriesTodoItemFromJSONTyped,
    TodoApiEndpointsTodosCompactQueriesTodoItemToJSON,
    TodoApiEndpointsTodosCompactQueriesTodoItemToJSONTyped,
} from './TodoApiEndpointsTodosCompactQueriesTodoItem';

/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosCompactQueriesListTodosResponse
 */
export interface TodoApiEndpointsTodosCompactQueriesListTodosResponse {
    /**
     * 
     * @type {Array<TodoApiEndpointsTodosCompactQueriesTodoItem>}
     * @memberof TodoApiEndpointsTodosCompactQueriesListTodosResponse
     */
    items?: Array<TodoApiEndpointsTodosCompactQueriesTodoItem> | null;
    /**
     * 
     * @type {number}
     * @memberof TodoApiEndpointsTodosCompactQueriesListTodosResponse
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosCompactQueriesListTodosResponse interface.
 */
export function instanceOfTodoApiEndpointsTodosCompactQueriesListTodosResponse(value: object): value is TodoApiEndpointsTodosCompactQueriesListTodosResponse {
    return true;
}

export function TodoApiEndpointsTodosCompactQueriesListTodosResponseFromJSON(json: any): TodoApiEndpointsTodosCompactQueriesListTodosResponse {
    return TodoApiEndpointsTodosCompactQueriesListTodosResponseFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCompactQueriesListTodosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosCompactQueriesListTodosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TodoApiEndpointsTodosCompactQueriesTodoItemFromJSON)),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function TodoApiEndpointsTodosCompactQueriesListTodosResponseToJSON(json: any): TodoApiEndpointsTodosCompactQueriesListTodosResponse {
    return TodoApiEndpointsTodosCompactQueriesListTodosResponseToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCompactQueriesListTodosResponseToJSONTyped(value?: TodoApiEndpointsTodosCompactQueriesListTodosResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TodoApiEndpointsTodosCompactQueriesTodoItemToJSON)),
        'totalCount': value['totalCount'],
    };
}

