/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosListTodosTodoItem
 */
export interface TodoApiEndpointsTodosListTodosTodoItem {
    /**
     * 
     * @type {number}
     * @memberof TodoApiEndpointsTodosListTodosTodoItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TodoApiEndpointsTodosListTodosTodoItem
     */
    title?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoApiEndpointsTodosListTodosTodoItem
     */
    done?: boolean;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosListTodosTodoItem interface.
 */
export function instanceOfTodoApiEndpointsTodosListTodosTodoItem(value: object): value is TodoApiEndpointsTodosListTodosTodoItem {
    return true;
}

export function TodoApiEndpointsTodosListTodosTodoItemFromJSON(json: any): TodoApiEndpointsTodosListTodosTodoItem {
    return TodoApiEndpointsTodosListTodosTodoItemFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosListTodosTodoItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosListTodosTodoItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'done': json['done'] == null ? undefined : json['done'],
    };
}

export function TodoApiEndpointsTodosListTodosTodoItemToJSON(json: any): TodoApiEndpointsTodosListTodosTodoItem {
    return TodoApiEndpointsTodosListTodosTodoItemToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosListTodosTodoItemToJSONTyped(value?: TodoApiEndpointsTodosListTodosTodoItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'done': value['done'],
    };
}

