/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosCreateTodoCreateTodoResponse
 */
export interface TodoApiEndpointsTodosCreateTodoCreateTodoResponse {
    /**
     * 
     * @type {number}
     * @memberof TodoApiEndpointsTodosCreateTodoCreateTodoResponse
     */
    id?: number;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosCreateTodoCreateTodoResponse interface.
 */
export function instanceOfTodoApiEndpointsTodosCreateTodoCreateTodoResponse(value: object): value is TodoApiEndpointsTodosCreateTodoCreateTodoResponse {
    return true;
}

export function TodoApiEndpointsTodosCreateTodoCreateTodoResponseFromJSON(json: any): TodoApiEndpointsTodosCreateTodoCreateTodoResponse {
    return TodoApiEndpointsTodosCreateTodoCreateTodoResponseFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCreateTodoCreateTodoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosCreateTodoCreateTodoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TodoApiEndpointsTodosCreateTodoCreateTodoResponseToJSON(json: any): TodoApiEndpointsTodosCreateTodoCreateTodoResponse {
    return TodoApiEndpointsTodosCreateTodoCreateTodoResponseToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCreateTodoCreateTodoResponseToJSONTyped(value?: TodoApiEndpointsTodosCreateTodoCreateTodoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

