/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest
 */
export interface TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest {
    /**
     * 
     * @type {string}
     * @memberof TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest
     */
    done?: boolean;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest interface.
 */
export function instanceOfTodoApiEndpointsTodosCompactCommandsUpdateTodoRequest(value: object): value is TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TodoApiEndpointsTodosCompactCommandsUpdateTodoRequestFromJSON(json: any): TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest {
    return TodoApiEndpointsTodosCompactCommandsUpdateTodoRequestFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCompactCommandsUpdateTodoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'done': json['done'] == null ? undefined : json['done'],
    };
}

export function TodoApiEndpointsTodosCompactCommandsUpdateTodoRequestToJSON(json: any): TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest {
    return TodoApiEndpointsTodosCompactCommandsUpdateTodoRequestToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCompactCommandsUpdateTodoRequestToJSONTyped(value?: TodoApiEndpointsTodosCompactCommandsUpdateTodoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'done': value['done'],
    };
}

