/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosCompactCommandsCreateTodoResponse
 */
export interface TodoApiEndpointsTodosCompactCommandsCreateTodoResponse {
    /**
     * 
     * @type {number}
     * @memberof TodoApiEndpointsTodosCompactCommandsCreateTodoResponse
     */
    id?: number;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosCompactCommandsCreateTodoResponse interface.
 */
export function instanceOfTodoApiEndpointsTodosCompactCommandsCreateTodoResponse(value: object): value is TodoApiEndpointsTodosCompactCommandsCreateTodoResponse {
    return true;
}

export function TodoApiEndpointsTodosCompactCommandsCreateTodoResponseFromJSON(json: any): TodoApiEndpointsTodosCompactCommandsCreateTodoResponse {
    return TodoApiEndpointsTodosCompactCommandsCreateTodoResponseFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCompactCommandsCreateTodoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosCompactCommandsCreateTodoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function TodoApiEndpointsTodosCompactCommandsCreateTodoResponseToJSON(json: any): TodoApiEndpointsTodosCompactCommandsCreateTodoResponse {
    return TodoApiEndpointsTodosCompactCommandsCreateTodoResponseToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCompactCommandsCreateTodoResponseToJSONTyped(value?: TodoApiEndpointsTodosCompactCommandsCreateTodoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

