/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TodoApiEndpointsTodosListTodosTodoItem } from './TodoApiEndpointsTodosListTodosTodoItem';
import {
    TodoApiEndpointsTodosListTodosTodoItemFromJSON,
    TodoApiEndpointsTodosListTodosTodoItemFromJSONTyped,
    TodoApiEndpointsTodosListTodosTodoItemToJSON,
    TodoApiEndpointsTodosListTodosTodoItemToJSONTyped,
} from './TodoApiEndpointsTodosListTodosTodoItem';

/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosListTodosListTodosResponse
 */
export interface TodoApiEndpointsTodosListTodosListTodosResponse {
    /**
     * 
     * @type {Array<TodoApiEndpointsTodosListTodosTodoItem>}
     * @memberof TodoApiEndpointsTodosListTodosListTodosResponse
     */
    items?: Array<TodoApiEndpointsTodosListTodosTodoItem> | null;
    /**
     * 
     * @type {number}
     * @memberof TodoApiEndpointsTodosListTodosListTodosResponse
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosListTodosListTodosResponse interface.
 */
export function instanceOfTodoApiEndpointsTodosListTodosListTodosResponse(value: object): value is TodoApiEndpointsTodosListTodosListTodosResponse {
    return true;
}

export function TodoApiEndpointsTodosListTodosListTodosResponseFromJSON(json: any): TodoApiEndpointsTodosListTodosListTodosResponse {
    return TodoApiEndpointsTodosListTodosListTodosResponseFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosListTodosListTodosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosListTodosListTodosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TodoApiEndpointsTodosListTodosTodoItemFromJSON)),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function TodoApiEndpointsTodosListTodosListTodosResponseToJSON(json: any): TodoApiEndpointsTodosListTodosListTodosResponse {
    return TodoApiEndpointsTodosListTodosListTodosResponseToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosListTodosListTodosResponseToJSONTyped(value?: TodoApiEndpointsTodosListTodosListTodosResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TodoApiEndpointsTodosListTodosTodoItemToJSON)),
        'totalCount': value['totalCount'],
    };
}

