/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest
 */
export interface TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest {
    /**
     * 
     * @type {string}
     * @memberof TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest
     */
    done?: boolean;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest interface.
 */
export function instanceOfTodoApiEndpointsTodosUpdateTodoUpdateTodoRequest(value: object): value is TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TodoApiEndpointsTodosUpdateTodoUpdateTodoRequestFromJSON(json: any): TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest {
    return TodoApiEndpointsTodosUpdateTodoUpdateTodoRequestFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosUpdateTodoUpdateTodoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'done': json['done'] == null ? undefined : json['done'],
    };
}

export function TodoApiEndpointsTodosUpdateTodoUpdateTodoRequestToJSON(json: any): TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest {
    return TodoApiEndpointsTodosUpdateTodoUpdateTodoRequestToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosUpdateTodoUpdateTodoRequestToJSONTyped(value?: TodoApiEndpointsTodosUpdateTodoUpdateTodoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'done': value['done'],
    };
}

