/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosCompactQueriesTodoItem
 */
export interface TodoApiEndpointsTodosCompactQueriesTodoItem {
    /**
     * 
     * @type {number}
     * @memberof TodoApiEndpointsTodosCompactQueriesTodoItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TodoApiEndpointsTodosCompactQueriesTodoItem
     */
    title?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoApiEndpointsTodosCompactQueriesTodoItem
     */
    done?: boolean;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosCompactQueriesTodoItem interface.
 */
export function instanceOfTodoApiEndpointsTodosCompactQueriesTodoItem(value: object): value is TodoApiEndpointsTodosCompactQueriesTodoItem {
    return true;
}

export function TodoApiEndpointsTodosCompactQueriesTodoItemFromJSON(json: any): TodoApiEndpointsTodosCompactQueriesTodoItem {
    return TodoApiEndpointsTodosCompactQueriesTodoItemFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCompactQueriesTodoItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosCompactQueriesTodoItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'done': json['done'] == null ? undefined : json['done'],
    };
}

export function TodoApiEndpointsTodosCompactQueriesTodoItemToJSON(json: any): TodoApiEndpointsTodosCompactQueriesTodoItem {
    return TodoApiEndpointsTodosCompactQueriesTodoItemToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCompactQueriesTodoItemToJSONTyped(value?: TodoApiEndpointsTodosCompactQueriesTodoItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'done': value['done'],
    };
}

