/* tslint:disable */
/* eslint-disable */
/**
 * TodoAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoApiEndpointsTodosCompactQueriesGetTodoResponse
 */
export interface TodoApiEndpointsTodosCompactQueriesGetTodoResponse {
    /**
     * 
     * @type {string}
     * @memberof TodoApiEndpointsTodosCompactQueriesGetTodoResponse
     */
    title?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TodoApiEndpointsTodosCompactQueriesGetTodoResponse
     */
    done?: boolean;
}

/**
 * Check if a given object implements the TodoApiEndpointsTodosCompactQueriesGetTodoResponse interface.
 */
export function instanceOfTodoApiEndpointsTodosCompactQueriesGetTodoResponse(value: object): value is TodoApiEndpointsTodosCompactQueriesGetTodoResponse {
    return true;
}

export function TodoApiEndpointsTodosCompactQueriesGetTodoResponseFromJSON(json: any): TodoApiEndpointsTodosCompactQueriesGetTodoResponse {
    return TodoApiEndpointsTodosCompactQueriesGetTodoResponseFromJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCompactQueriesGetTodoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoApiEndpointsTodosCompactQueriesGetTodoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'done': json['done'] == null ? undefined : json['done'],
    };
}

export function TodoApiEndpointsTodosCompactQueriesGetTodoResponseToJSON(json: any): TodoApiEndpointsTodosCompactQueriesGetTodoResponse {
    return TodoApiEndpointsTodosCompactQueriesGetTodoResponseToJSONTyped(json, false);
}

export function TodoApiEndpointsTodosCompactQueriesGetTodoResponseToJSONTyped(value?: TodoApiEndpointsTodosCompactQueriesGetTodoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'done': value['done'],
    };
}

